model:
  name: transunet
  use_pretrained: true
  img_size: 224

experiment:
  name: transunet_hu_focal_tversky_epoch30_pretrained
  seed: 42

data:
  root_dir: "./src/content/data"          # contains train/ val/ test/ subâ€‘dirs
  threshold: 0.3

train:
  batch_size: 4
  epochs: 30
  lr: 0.0001
  loss: focal_tversky
  save_dir: outputs/transunet_hu_focal_tversky_epoch30_pretrained
  num_workers: 4
  patience: 10

eval:
  visualize: true