model:
  name: unet
  use_pretrained: true
  img_size: 512

experiment:
  name: unet_hu_dice_focal_epoch50_pretrained
  seed: 42

data:
  root_dir: "C:/Users/Hyojun Park/Paper/new_data/output_dataset"          # contains train/ val/ test/ subâ€‘dirs
  threshold: 0.3

train:
  batch_size: 4
  epochs: 100
  lr: 0.0001
  loss: dice_focal
  save_dir: outputs/unet_hu_dice_focal_epoch50_pretrained
  num_workers: 4
  patience: 15
  k_folds: 5

eval:
  visualize: true